### ISSUE TITLE
Market analysis

### ISSUE THREAD

**Issue by AxessLab** [AxessLab/typing#1]
Review other apps that exist today, especially ones who claim to work well for blind users.

Document the findings and take note of features that are good and problems that no one has managed to solve yet.

- Add a list of these, with analysis and test comments for each, to this Git wiki.

**Comment by sofieaxesslab** [comment]
Starting summery in swedish in separate document.

**Comment by sofieaxesslab** [comment]
Finished onlys need translation to english to be able to put into wiki/blogpost to share insights to the community.
