### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by AxessLab** [AxessLab/typing#2]
Based on the market analysis and interviews with users or user representatives, write down a list of features that should be in a great keyboard tutoring tool.

Also write down non-functional requirements like "should not require mouse" or "should work for any language and keyboard layout", et cetera.

Decide on what to focus on for the prototype project, like:

* (mobile / tablet / desktop)
* (physical keyboard / on screen keyboard)
* (web app / native app)
* (adults / children)
* (screen reader competence - none / some / expert)

**Comment by AxessLab** [comment]
@sofieaxesslab Add more to this issue when first user research meetup has been conducted.

**Comment by sofieaxesslab** [comment]
Started from ux and product owner perspective, a list of requirement and user stories.  Needs discussions with team and scrum master to be able to put in a backlog for sprint 1.
