### ISSUE TITLE
Add additional steps to our prototype in Adobe XD

### ISSUE THREAD

**Issue by duff92** [AxessLab/typing#57]
We need to add additional steps for our prototype to include more tasks than just "F" and "J". This to better describe the user journey in our application.

**Comment by sofieaxesslab** [comment]
Final prototype: 
View: 
https://xd.adobe.com/view/17e1bf13-8e31-4785-473d-123db6fbb103-61d0/?hints=off 

Development: 
https://xd.adobe.com/spec/cf29f8ef-dcb1-4a79-7d0c-5300d0e113f3-b918/
